In [ ]:
import numpy as np
import sympy as sp
L = 20 #ft
L = 20*12
E = 29000 #ksi
A = 26.2 #in^2

r2 = np.sqrt(2)

Question 6: Write the displacement transformation matrix for each truss member.

In [ ]:
#Question 6       see lec 29 slide 11, that matrix can be applied to each member
mem_1_T = np.array([[0,-L/L,0,0],
                    [0,0,0,-L/L]])

mem_2_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_3_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_4_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_5_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_6_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_7_T = np.array([[1/r2,1/r2,0,0],          #diagonal
                    [0,0,1/r2,1/r2]])

mem_8_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_9_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_10_T = np.array([[L/L,0,0,0],
                    [0,0,L/L,0]])

mem_11_T = np.array([[0,-L/L,0,0],
                    [0,0,0,-L/L]])

mem_12_T = np.array([[1/r2,1/r2,0,0],          #diagonal
                    [0,0,1/r2,1/r2]])

mem_13_T = np.array([[0,-L/L,0,0],
                    [0,0,0,-L/L]])

mem_14_T = np.array([[1/r2,-1/r2,0,0],          #diagonal
                    [0,0,1/r2,-1/r2]])

mem_15_T = np.array([[0,-L/L,0,0],
                    [0,0,0,-L/L]])

mem_16_T = np.array([[1/r2,-1/r2,0,0],          #diagonal
                    [0,0,1/r2,-1/r2]])

mem_17_T = np.array([[0,-L/L,0,0],
                    [0,0,0,-L/L]])

print(mem_1_T)
print(mem_2_T)
print(mem_3_T)
print(mem_4_T)
print(mem_5_T)
print(mem_6_T)
print(mem_7_T)
print(mem_8_T)
print(mem_9_T)
print(mem_10_T)
print(mem_11_T)
print(mem_12_T)
print(mem_13_T)
print(mem_14_T)
print(mem_15_T)
print(mem_16_T)
print(mem_17_T)

[[ 0. -1.  0.  0.]
 [ 0.  0.  0. -1.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[0.70710678 0.70710678 0.         0.        ]
 [0.         0.         0.70710678 0.70710678]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0. -1.  0.  0.]
 [ 0.  0.  0. -1.]]
[[0.70710678 0.70710678 0.         0.        ]
 [0.         0.         0.70710678 0.70710678]]
[[ 0. -1.  0.  0.]
 [ 0.  0.  0. -1.]]
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]]
[[ 0. -1.  0.  0.]
 [ 0.  0.  0. -1.]]
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]]
[[ 0. -1.  0.  0.]
 [ 0.  0.  0. -1.]]


Question 7: Assemble the global stiffness matrix.

In [ ]:
#Question 7
#matrix is same lambdas are different, global can be found in lec 30
N = 20 #number of DOF
K = np.zeros((N,N))
guide = np.array([0, 1, 2, 3])

k_mem_1 = ((E*A)/L) * np.array([[0, 0, 0, 0],
                                [0, 1, 0, -1],
                                [0, 0, 0, 0],
                                [0, -1, 0, 1]])

k_mem_2 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_3 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_4 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_5 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_6 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_7 = ((E*A)/L) * np.array([[1/2, 1/2, -1/2, -1/2],      #diagonal
                                [1/2, 1/2, -1/2, -1/2],
                                [-1/2, -1/2, 1/2, 1/2],
                                [-1/2, -1/2, 1/2, 1/2]])

k_mem_8 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_9 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_10 = ((E*A)/L) * np.array([[1, 0, -1, 0],
                                [0, 0, 0, 0],
                                [-1, 0, 1, 0],
                                [0, 0, 0, 0]])

k_mem_11 = ((E*A)/L) * np.array([[0, 0, 0, 0],
                                [0, 1, 0, -1],
                                [0, 0, 0, 0],
                                [0, -1, 0, 1]])

k_mem_12 = ((E*A)/L) * np.array([[1/2, 1/2, -1/2, -1/2],      #diagonal
                                [1/2, 1/2, -1/2, -1/2],
                                [-1/2, -1/2, 1/2, 1/2],
                                [-1/2, -1/2, 1/2, 1/2]])

k_mem_13 = ((E*A)/L) * np.array([[0, 0, 0, 0],
                                [0, 1, 0, -1],
                                [0, 0, 0, 0],
                                [0, -1, 0, 1]])

k_mem_14 = ((E*A)/L) * np.array([[1/2, -1/2, -1/2, 1/2],      #diagonal
                                [-1/2, 1/2, 1/2, -1/2],
                                [-1/2, 1/2, 1/2, -1/2],
                                [1/2, -1/2, -1/2, 1/2]])

k_mem_15 = ((E*A)/L) * np.array([[0, 0, 0, 0],
                                [0, 1, 0, -1],
                                [0, 0, 0, 0],
                                [0, -1, 0, 1]])

k_mem_16 = ((E*A)/L) * np.array([[1/2, -1/2, -1/2, 1/2],      #diagonal
                                [-1/2, 1/2, 1/2, -1/2],
                                [-1/2, 1/2, 1/2, -1/2],
                                [1/2, -1/2, -1/2, 1/2]])

k_mem_17 = ((E*A)/L) * np.array([[0, 0, 0, 0],
                                [0, 1, 0, -1],
                                [0, 0, 0, 0],
                                [0, -1, 0, 1]])

guideK1 = np.array([19-1, 20-1, 1-1, 2-1])
for i in guide:
  for j in guide:
    K[guideK1[i],guideK1[j]] = k_mem_1[i,j] + K[guideK1[i],guideK1[j]]

guideK2 = np.array([1-1, 2-1, 3-1, 4-1])
for i in guide:
  for j in guide:
    K[guideK2[i],guideK2[j]] = k_mem_2[i,j] + K[guideK2[i],guideK2[j]]

guideK3 = np.array([3-1, 4-1, 5-1, 6-1])
for i in guide:
  for j in guide:
    K[guideK3[i],guideK3[j]] = k_mem_3[i,j] + K[guideK3[i],guideK3[j]]

guideK4 = np.array([5-1, 6-1, 7-1, 8-1])
for i in guide:
  for j in guide:
    K[guideK4[i],guideK4[j]] = k_mem_4[i,j] + K[guideK4[i],guideK4[j]]

guideK5 = np.array([7-1, 8-1, 9-1, 10-1])
for i in guide:
  for j in guide:
    K[guideK5[i],guideK5[j]] = k_mem_5[i,j] + K[guideK5[i],guideK5[j]]

guideK6 = np.array([19-1, 20-1, 17-1, 18-1])
for i in guide:
  for j in guide:
    K[guideK6[i],guideK6[j]] = k_mem_6[i,j] + K[guideK6[i],guideK6[j]]

guideK7 = np.array([1-1, 2-1, 17-1, 18-1])
for i in guide:
  for j in guide:
    K[guideK7[i],guideK7[j]] = k_mem_7[i,j] + K[guideK7[i],guideK7[j]]

guideK8 = np.array([17-1, 18-1, 15-1, 16-1])
for i in guide:
  for j in guide:
    K[guideK8[i],guideK8[j]] = k_mem_8[i,j] + K[guideK8[i],guideK8[j]]

guideK9 = np.array([15-1, 16-1, 13-1, 14-1])
for i in guide:
  for j in guide:
    K[guideK9[i],guideK9[j]] = k_mem_9[i,j] + K[guideK9[i],guideK9[j]]

guideK10 = np.array([13-1, 14-1, 11-1, 12-1])
for i in guide:
  for j in guide:
    K[guideK10[i],guideK10[j]] = k_mem_10[i,j] + K[guideK10[i],guideK10[j]]

guideK11 = np.array([17-1, 18-1, 3-1, 4-1])
for i in guide:
  for j in guide:
    K[guideK11[i],guideK11[j]] = k_mem_11[i,j] + K[guideK11[i],guideK11[j]]

guideK12 = np.array([3-1, 4-1, 15-1, 16-1])
for i in guide:
  for j in guide:
    K[guideK12[i],guideK12[j]] = k_mem_12[i,j] + K[guideK12[i],guideK12[j]]

guideK13 = np.array([15-1, 16-1, 5-1, 6-1])
for i in guide:
  for j in guide:
    K[guideK13[i],guideK13[j]] = k_mem_13[i,j] + K[guideK13[i],guideK13[j]]

guideK14 = np.array([15-1, 16-1, 7-1, 8-1])
for i in guide:
  for j in guide:
    K[guideK14[i],guideK14[j]] = k_mem_14[i,j] + K[guideK14[i],guideK14[j]]

guideK15 = np.array([13-1, 14-1, 7-1, 8-1])
for i in guide:
  for j in guide:
    K[guideK15[i],guideK15[j]] = k_mem_15[i,j] + K[guideK15[i],guideK15[j]]

guideK16 = np.array([13-1, 14-1, 9-1, 10-1])
for i in guide:
  for j in guide:
    K[guideK16[i],guideK16[j]] = k_mem_16[i,j] + K[guideK16[i],guideK16[j]]

guideK17 = np.array([11-1, 12-1, 9-1, 10-1])
for i in guide:
  for j in guide:
    K[guideK17[i],guideK17[j]] = k_mem_17[i,j] + K[guideK17[i],guideK17[j]]

print(K)


[[ 4748.75        1582.91666667 -3165.83333333     0.
      0.             0.             0.             0.
      0.             0.             0.             0.
      0.             0.             0.             0.
  -1582.91666667 -1582.91666667     0.             0.        ]
 [ 1582.91666667  4748.75           0.             0.
      0.             0.             0.             0.
      0.             0.             0.             0.
      0.             0.             0.             0.
  -1582.91666667 -1582.91666667     0.         -3165.83333333]
 [-3165.83333333     0.          7914.58333333  1582.91666667
  -3165.83333333     0.             0.             0.
      0.             0.             0.             0.
      0.             0.         -1582.91666667 -1582.91666667
      0.             0.             0.             0.        ]
 [    0.             0.          1582.91666667  4748.75
      0.             0.             0.             0.
      0.             0.             0

Question 8: Solve the linear system in Python and calculate the forces in the truss members.
Compare with the result found in Question 4.

Question 9: Determine the mid-span deflection in the vertical direction. Compare with the results
found in questions 2 and 5.


In [ ]:
#Question 8&9

import numpy as np
import sympy as sp

# Question 8: Solve for displacements and calculate member forces

# Define the force vector

F = np.zeros(N)

F[3] = -10   # joint 2
F[5] = -10   # joint 3
F[7] = -10   # joint 4

# boundary conditions

fixed_dofs = [0, 1, 9]
free_dofs = [i for i in range(N) if i not in fixed_dofs]

# stiffness matrix
K_ff = K[np.ix_(free_dofs, free_dofs)]
F_f = F[free_dofs]

#free displacements
U_free = np.linalg.solve(K_ff, F_f)

# displacement vector
U = np.zeros(N)
for i, dof in enumerate(free_dofs):
    U[dof] = U_free[i]

print("Nodal displacements (inches):")
for i in range(N):
    print(f"  DOF {i+1}: {U[i]:.6f} in")

# Calculating member forces:
member_guides = [
    guideK1, guideK2, guideK3, guideK4, guideK5,
    guideK6, guideK7, guideK8, guideK9, guideK10,
    guideK11, guideK12, guideK13, guideK14, guideK15,
    guideK16, guideK17
]
member_T = [
    mem_1_T, mem_2_T, mem_3_T, mem_4_T, mem_5_T,
    mem_6_T, mem_7_T, mem_8_T, mem_9_T, mem_10_T,
    mem_11_T, mem_12_T, mem_13_T, mem_14_T, mem_15_T,
    mem_16_T, mem_17_T
]


print("\nMember Forces (kips):")
for m in range(17):
    guide = member_guides[m]
    T = member_T[m]
    u_local = np.array([U[guide[0]], U[guide[1]], U[guide[2]], U[guide[3]]])
    # Force = (EA/L) * [−1, 1] @ T @ u_local  (deformation in local coords)
    deformation = T @ u_local  # [u_local_i, u_local_j]
    force = (E * A / L) * (deformation[1] - deformation[0])
    print(f"  Member {m+1}: {force:.2f} kips")

Nodal displacements (inches):
  DOF 1: 0.000000 in
  DOF 2: 0.000000 in
  DOF 3: 0.004738 in
  DOF 4: -0.030008 in
  DOF 5: 0.011056 in
  DOF 6: -0.042643 in
  DOF 7: 0.017373 in
  DOF 8: -0.030008 in
  DOF 9: 0.022111 in
  DOF 10: 0.000000 in
  DOF 11: 0.006317 in
  DOF 12: 0.000000 in
  DOF 13: 0.006317 in
  DOF 14: -0.025270 in
  DOF 15: 0.011056 in
  DOF 16: -0.039484 in
  DOF 17: 0.015794 in
  DOF 18: -0.025270 in
  DOF 19: 0.015794 in
  DOF 20: 0.000000 in

Member Forces (kips):
  Member 1: 0.00 kips
  Member 2: 15.00 kips
  Member 3: 20.00 kips
  Member 4: 20.00 kips
  Member 5: 15.00 kips
  Member 6: 0.00 kips
  Member 7: -21.21 kips
  Member 8: -15.00 kips
  Member 9: -15.00 kips
  Member 10: 0.00 kips
  Member 11: 15.00 kips
  Member 12: -7.07 kips
  Member 13: 10.00 kips
  Member 14: -7.07 kips
  Member 15: 15.00 kips
  Member 16: -21.21 kips
  Member 17: 0.00 kips
